<?php
session_start();
if (isset($_SESSION['logged_in']) && $_SESSION['logged_in'] === true) {
    // User is logged in, show index page content
    // You can also display user information from $_SESSION here
} else {
    // User is not logged in, redirect to login page
    header("Location: logout.php");
    exit();
}
error_reporting(E_ALL);
ini_set('display_errors', 1);

require("./fpdf/fpdf.php");

class PDF extends FPDF {
    function Header() {
        // Add company name and logo
        $this->Image('assets/img/logo kpl.jpg', 10, 10, 30);
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 10, 'Company Name: KPL Visitors', 0, 1, 'C');
        
        // Add report title
        $this->SetFont('Arial', 'B', 16);
        $this->Cell(0, 15, 'Visitor Attendance Report', 0, 1, 'C');
        
        // Add report date
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 10, 'Report Date: ' . date('Y-m-d'), 0, 1, 'C');
        
        // Add spacing after header
        $this->Ln(10);
        
        // Table headers
        $header = array("Event Name", "M", "F", "Child", "Student", "Adult");
        $this->SetFillColor(200, 220, 255);
        $this->SetFont('Arial', 'B', 10);

        // Display headers
        $w = array(60, 20, 20, 25, 25, 25);
        for ($i = 0; $i < count($header); $i++) {
            $this->Cell($w[$i], 10, $header[$i], 1, 0, 'C', 1);
        }
        $this->Ln();
    }

    function Footer() {
        // Footer content (if needed)
        // Add "Generated by" information
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by: Your Name', 0, 0, 'L');
        
        // Add signature placeholder
        $this->Cell(0, 10, 'Signature:', 0, 0, 'R');
    }
}

// Database configuration
$host = "localhost";
$username = "root";
$password = "";
$database = "KPLV_Db";

// Create a database connection
$conn = new mysqli($host, $username, $password, $database);

// Check if the connection was successful
if ($conn->connect_error) {
    die("Database connection failed: " . $conn->connect_error);
}

// Create a PDF instance
$pdf = new PDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 12);

// Your existing code for fetching data from the database
// ...

// Initialize totals
$totalMale = 0;
$totalFemale = 0;
$totalChild = 0;
$totalYoung = 0;
$totalAdult = 0;

// Loop through query results and display data
$query = mysqli_query($conn, "SELECT e.eName, 
    SUM(CASE WHEN v.sex = 'Male' THEN 1 ELSE 0 END) AS male_count, 
    SUM(CASE WHEN v.sex = 'Female' THEN 1 ELSE 0 END) AS female_count, 
    SUM(CASE WHEN v.category = 'child' THEN 1 ELSE 0 END) AS child_category, 
    SUM(CASE WHEN v.category = 'student' THEN 1 ELSE 0 END) AS young_category, 
    SUM(CASE WHEN v.category = 'adult' THEN 1 ELSE 0 END) AS adult_category 
    FROM attendance a JOIN event e ON e.eCode = a.reason 
    JOIN vistors v ON v.vistorCode = a.vistor GROUP BY e.eName");
if (!$query) {
    die("Query failed: " . mysqli_error($conn));
}

$pdf->SetFont('Arial', '', 10);
$w = array(60, 20, 20, 25, 25, 25); // Define table column widths

while ($row = mysqli_fetch_assoc($query)) {
    // Display table rows
    $pdf->Cell($w[0], 10, $row['eName'], 1);
    $pdf->Cell($w[1], 10, $row['male_count'], 1, 0, 'C');
    $pdf->Cell($w[2], 10, $row['female_count'], 1, 0, 'C');
    $pdf->Cell($w[3], 10, $row['child_category'], 1, 0, 'C');
    $pdf->Cell($w[4], 10, $row['young_category'], 1, 0, 'C');
    $pdf->Cell($w[5], 10, $row['adult_category'], 1, 0, 'C');
    $pdf->Ln();

    // Update totals
    $totalMale += $row['male_count'];
    $totalFemale += $row['female_count'];
    $totalChild += $row['child_category'];
    $totalYoung += $row['young_category'];
    $totalAdult += $row['adult_category'];
}

// Display totals
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell($w[0], 10, 'Total', 1);
$pdf->Cell($w[1], 10, $totalMale, 1, 0, 'C');
$pdf->Cell($w[2], 10, $totalFemale, 1, 0, 'C');
$pdf->Cell($w[3], 10, $totalChild, 1, 0, 'C');
$pdf->Cell($w[4], 10, $totalYoung, 1, 0, 'C');
$pdf->Cell($w[5], 10, $totalAdult, 1, 0, 'C');
$pdf->Ln();


$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(0, 10, 'Generated by: Your Name', 0, 0, 'L');
$pdf->Cell(0, 10, 'Signature:', 0, 0, 'R');
// Output the PDF
$pdf->Output();
?>
